apiVersion: v1
kind: Secret
metadata:
  name: {{ include "waf-downloader.fullname" . }}
  namespace: {{ include "waf-downloader.fullname" . }}
  labels:
    {{- include "waf-downloader.labels" . | nindent 4 }}
type: Opaque
data:
  CLOUDFLARE_API_TOKEN: {{ .Values.cloudflare.apiToken | b64enc | quote }}
  DB_CONN_STR: {{ .Values.outputs.dbConnStr | b64enc | quote }}
