name: CI/CD
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v0.*"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install toml
      - id: releasetools
        uses: releasetools/bash@v0
        with:
          version: "v0.0.6"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.39.2
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          task create-venv
          eval "$(task venv)"
          task install

      - name: Run linters
        run: |
          eval "$(task venv)"
          task lint

      - name: Run tests
        run: |
          eval "$(task venv)"
          pytest tests

  build:
    name: Build Python package
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v0.')
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - id: releasetools
        uses: releasetools/bash@v0
        with:
          version: "v0.0.6"

      - name: Install release tools dependencies
        run: pip install toml

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.39.2
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          task create-venv
          eval "$(task venv)"
          task install

      - name: Set the correct (tag) version
        run: |
          VERSION="$(rt git::version_or_sha)"
          echo "Updating version in '$VERSION_FILE' to: $VERSION" >&2
          echo "$VERSION" > ./VERSION

      - name: Build
        run: |
          eval "$(task venv)"
          task build

      - name: Cache build
        uses: actions/cache/save@v4
        with:
          path: .
          key: ${{ runner.os }}-build-${{ github.sha }}

  publish:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v0.')
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Restore working directory
        uses: actions/cache/restore@v4
        with:
          path: .
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Upload to PyPI (test)
        env:
          TESTPYPI_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
        run: |
          eval "$(task venv)"
          task publish-test

      - name: Upload to PyPI (prod)
        env:
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          eval "$(task venv)"
          task publish

      - name: Verify package install from PyPI
        run: |
          eval "$(task venv)"
          task publish-verify

  push-docker:
    name: Build and/or push to Docker Hub
    runs-on: ubuntu-latest
    needs: publish

    permissions:
      actions: read
      packages: write
      contents: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - id: releasetools
        uses: releasetools/bash@v0
        with:
          version: "v0.0.6"

      - name: Install release tools dependencies
        run: pip install toml

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.39.2
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore working directory
        uses: actions/cache/restore@v4
        with:
          path: .
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Configuring developer tools
      #   run: |
      #     # task create-venv
      #     # eval "$(task venv)"
      #     # task install

      - name: Generate build tags
        run: |
          OWNER_REPO="$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" # format: org/repo
          echo "OWNER_REPO=$OWNER_REPO" >> "$GITHUB_ENV"

          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          echo "REPO_NAME=$REPO_NAME" >> "$GITHUB_ENV"

          VERSION="$(rt git::version_or_sha)"
          echo "Updating version in '$VERSION_FILE' to: $VERSION" >&2
          echo "$VERSION" > ./VERSION
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Log in to Docker Hub
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v0.')
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker multiplatform image
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64,linux/amd64
          # Only push image to registries on tag pushes
          push: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v0.') }}
          labels: |
            org.opencontainers.image.title=Cloudflare Web Application Firewall log downloader
            org.opencontainers.image.description="Cloudflare Web Application Firewall log downloader for a specified zone and time range"
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=Apache-2.0
          tags: |
            docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ github.sha }}
            docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.VERSION }}
            docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:latest

      - name: Generate SBOM (Docker Hub)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v0.')
        uses: anchore/sbom-action@v0
        with:
          image: docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.VERSION }}
          artifact-name: sbom_docker_${{ env.REPO_NAME }}_${{ env.VERSION }}.spdx.json

      - name: Generate artifact attestation for Docker Hub
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v0.')
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

  push-ghcr:
    name: Build and/or push to GitHub Container Registry
    runs-on: ubuntu-latest
    needs: publish

    permissions:
      actions: read
      packages: write
      contents: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Restore working directory
        uses: actions/cache/restore@v4
        with:
          path: .
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.39.2
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - id: releasetools
        uses: releasetools/bash@v0
        with:
          version: "v0.0.6"

      - name: Install release tools dependencies
        run: pip install toml

      # - name: Configuring developer tools
      #   run: |
      #     task create-venv
      #     # eval "$(task venv)"
      #     # task install

      - name: Generate build tags
        run: |
          OWNER_REPO="$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" # format: org/repo
          echo "OWNER_REPO=$OWNER_REPO" >> "$GITHUB_ENV"

          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          echo "REPO_NAME=$REPO_NAME" >> "$GITHUB_ENV"

          VERSION="$(rt git::version_or_sha)"
          echo "Updating version in '$VERSION_FILE' to: $VERSION" >&2
          echo "$VERSION" > ./VERSION
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v0.')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Build Docker multiplatform image
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64,linux/amd64
          # Only push image to registries on tag pushes
          push: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v0.') }}
          labels: |
            org.opencontainers.image.title=Cloudflare Web Application Firewall log downloader
            org.opencontainers.image.description="Cloudflare Web Application Firewall log downloader for a specified zone and time range"
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=Apache-2.0
          tags: |
            ghcr.io/${{ env.OWNER_REPO }}:${{ github.sha }}
            ghcr.io/${{ env.OWNER_REPO }}:${{ env.VERSION }}
            ghcr.io/${{ env.OWNER_REPO }}:latest

      - name: Generate SBOM
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v0.')
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ env.OWNER_REPO }}:${{ env.VERSION }}
          artifact-name: sbom_ghcr_${{ env.REPO_NAME }}_${{ env.VERSION }}.spdx.json

      - name: Generate artifact attestation
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v0.')
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ env.OWNER_REPO }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - push-docker
      - push-ghcr

    steps:
      - name: Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v0.')
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true
          # files: |
          #   sbom_ghcr_${{ env.REPO_NAME }}_${{ env.VERSION }}.spdx.json
          #   sbom_docker_${{ env.REPO_NAME }}_${{ env.VERSION }}.spdx.json

  helm:
    name: Publish Helm Chart
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v0.')
    runs-on: ubuntu-latest
    needs: release

    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.39.2e
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          task create-venv
          eval "$(task venv)"
          task install

      - name: Set chart version
        run: |
          task set-chart-version

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR" # "github-actions[bot]"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com" # "github-actions[bot]@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          skip_existing: true
