name: Publish Docker Image to GitHub Container Registry

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      id-token: write
      attestations: write

    env:
      REGISTRY: ghcr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configuring developer tools
        run: |
          task create-venv
          eval "$(task venv)"
          task setup

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Building and pushing Docker images
        id: build
        run: |
          eval "$(task venv)"
          source "scripts/functions.bash"

          OWNER_REPO="$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" # format: org/repo
          IMAGE_NAME="ghcr.io/$OWNER_REPO:${{ github.sha }}"
          TAG="$(get_tag_at_head)"
          if [ -z "$TAG" ]; then
            TAG="${{ github.sha }}"
          fi

          task docker-build -- \
            --platform linux/arm64,linux/x86_64 \
            --push \
            --tag "$IMAGE_NAME" \
            --tag "ghcr.io/$OWNER_REPO:$TAG" \
            --tag "ghcr.io/$OWNER_REPO:latest"

          # digest
          docker pull "$IMAGE_NAME"
          docker images
          set -vx
          docker images $IMAGE_NAME --format '{{.Digest}}'

          DOCKER_DIGEST="$(docker images $IMAGE_NAME --format '{{.Digest}}')"
          echo "digest=${DOCKER_DIGEST}" >&2
          echo "digest=${DOCKER_DIGEST}" >> "$GITHUB_OUTPUT"

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
