name: Test the Docker Image build

on:
  # Trigger on PRs
  pull_request:
    branches:
      - main
  # And on pushes to main
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.13"

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configuring developer tools
        run: |
          task create-venv
          eval "$(task venv)"
          task install

      - name: Generate build tags
        run: |
          eval "$(task venv)"
          source "scripts/functions.bash"

          OWNER_REPO="$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" # format: org/repo
          echo "OWNER_REPO=$OWNER_REPO" >> "$GITHUB_ENV"

          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          echo "REPO_NAME=$REPO_NAME" >> "$GITHUB_ENV"

          scripts/detect-and-set-tag-version.bash
          echo "VERSION=$(cat ${{ github.workspace }}/VERSION)" >> "$GITHUB_ENV"

      - name: Build Docker multiplatform image
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          labels: |
            org.opencontainers.image.title=Cloudflare Web Application Firewall log downloader
            org.opencontainers.image.description="Cloudflare Web Application Firewall log downloader for a specified zone and time range"
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=Apache-2.0
          tags: |
            ${{ env.REPO_NAME }}:${{ github.sha }}
            ghcr.io/${{ env.OWNER_REPO }}:${{ github.sha }}
            ghcr.io/${{ env.OWNER_REPO }}:${{ env.VERSION }}
            ghcr.io/${{ env.OWNER_REPO }}:latest
            docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ github.sha }}
            docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.VERSION }}
            docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:latest

      - name: Generate SBOM (GHCR)
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.REPO_NAME }}:${{ github.sha }}
